apiVersion: batch/v1
kind: Job
metadata:
  name: copy-job
spec:
  template:
    spec:
      containers:
      - name: copy-container
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "<h1>Hello from NFS!</h1>" > /data/index.html;
        volumeMounts:
        - name: nfs-volume
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-pvc
